spring: 
   profiles:
    active:
     - dev
---
spring:
   profiles:dev
   application:
      name: vooleservice-config-dev
---
spring:
   profiles:test
   application:
    name: vooleservice-config-test
