server:
    port: 9001
    
spring:
    profiles: dev
    application:
      name: ticket-provide-client

eureka:
    instance:
        prefer-ip-address: true
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
              defaultZone: http://server1:7001/eureka/
            
